### ISSUE TITLE
your code looks *remarkebly* resemble to mine..

### ISSUE THREAD

**Issue by yairEO** [p-m-p/jQuery-Stickybox#3]
you code looks a LOT like my Stikyfloat plugin, and the name as well.

can you please elaborate on this matter? why would you copy it and change claim as your own with minor changes?

**Comment by p-m-p** [comment]
So, without pointing out the obvious and stating the fact that I wrote this code two years ago where as your first commit was barely two months ago, I don't see how the actual source code is remotely similar.

Sure, if two people create a plugin that does the same thing chances are the code may be similar and even the name. Anyway... I could put it to you that you copied my code but then that'd just be trolling, right?

:trollface: :boom: - - - - - :gun:

**Comment by yairEO** [comment]
i've created it at 2009, and until recently it was free on the internet for
the last 3.5 years on many different sources..and honestly you names your
functions also quite like mine. when i wrote this plugin, it was the first
and only on the internet, so obviously i didn't copy anyone.

**Comment by p-m-p** [comment]
Good for you :kiss:
