### ISSUE TITLE
complete() function

### ISSUE THREAD

**Issue by ibanez0r** [p-m-p/jQuery-Stickybox#4]
Hi i recently started playing around with this code, I am trying to adapt it to a site, where, once the stickybox stops moving, it uses a plugin to pull data from the nearest element, which works great, however, defining a complete function to the animate call results in the complete function being called hundreds of times as the user scrolls, any idea off the top of your head a quick way to resolve that?

**Comment by p-m-p** [comment]
Try changing `.stop()` to `.stop(true)` to clear the queue. http://api.jquery.com/stop/

**Comment by ibanez0r** [comment]
awesome, thank-you

**Comment by p-m-p** [comment]
No problem.
